// Generated by CoffeeScript 1.6.3
/*
Todo.sort()
*/


(function() {
  this.Todo = (function() {
    Todo._storage = [];

    Todo._idCounter = 0;

    function Todo(name, completed) {
      this.name = name;
      this.completed = completed != null ? completed : false;
      this.id = Todo.generateID();
      Todo._storage.unshift(this);
      Todo.sort();
    }

    Todo.all = function() {
      return Todo._storage;
    };

    Todo.generateID = function() {
      return this._idCounter++;
    };

    Todo.find = function(id) {
      var index, t;
      return ((function() {
        var _i, _len, _ref, _results;
        _ref = Todo.all();
        _results = [];
        for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
          t = _ref[index];
          if (t.id === id) {
            _results.push(t);
          }
        }
        return _results;
      })())[0];
    };

    Todo.select = function(iterator) {
      var t, _i, _len, _ref, _results;
      _ref = Todo.all();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        t = _ref[_i];
        if (iterator(t)) {
          _results.push(t);
        }
      }
      return _results;
    };

    Todo.sort = function() {
      return Todo._storage.sort(function(a, b) {
        if (a.completed === b.completed) {
          return 0;
        } else if (a.completed < b.completed) {
          return 1;
        } else {
          return -1;
        }
      });
    };

    Todo.prototype.complete = function() {
      return this.completed = true;
    };

    Todo.prototype.destroy = function() {
      var index, t;
      return Todo._storage = (function() {
        var _i, _len, _ref, _results;
        _ref = Todo.all();
        _results = [];
        for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
          t = _ref[index];
          if (t.id !== this.id) {
            _results.push(index);
          }
        }
        return _results;
      }).call(this);
    };

    return Todo;

  })();

}).call(this);
